# Generated by Django 5.1.3 on 2024-11-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('tanggal_akhir_berlaku', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('potongan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_transaksi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jumlah_hari_berlaku', models.IntegerField()),
                ('kuota_penggunaan', models.IntegerField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
