# Generated by Django 5.1.3 on 2024-11-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subkategori_layanan', '0003_remove_subkategori_deskripsi_pekerja_deskripsi_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimoni',
        ),
    ]
