# Generated by Django 5.1.3 on 2024-11-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subkategori_layanan', '0004_delete_testimoni'),
    ]

    operations = [
        migrations.AddField(
            model_name='subkategori',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
