# Generated by Django 5.1.3 on 2024-11-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subkategori_layanan', '0005_subkategori_deskripsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subkategori',
            name='deskripsi',
            field=models.TextField(default='Deskripsi belum tersedia.'),
        ),
    ]
