# Generated by Django 5.1.3 on 2024-11-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subkategori_layanan', '0006_alter_subkategori_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesilayanan',
            name='sesi',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
