# Generated by Django 5.1.3 on 2024-11-25 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subkategori_layanan', '0007_sesilayanan_sesi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesilayanan',
            name='nama_layanan',
        ),
        migrations.AlterField(
            model_name='sesilayanan',
            name='subkategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesi_layanan', to='subkategori_layanan.subkategori'),
        ),
    ]
