# Generated by Django 5.1.3 on 2024-11-25 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subkategori_layanan', '0008_remove_sesilayanan_nama_layanan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesilayanan',
            name='subkategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subkategori_layanan.subkategori'),
        ),
        migrations.AlterField(
            model_name='subkategori',
            name='tipe',
            field=models.CharField(max_length=10),
        ),
    ]
