# Generated by Django 5.1.3 on 2024-11-11 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subkategori',
            name='tipe',
            field=models.CharField(choices=[('pengguna', 'Pengguna'), ('pekerja', 'Pekerja')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subkategori',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kategori'),
        ),
        migrations.AlterField(
            model_name='subkategori',
            name='nama',
            field=models.CharField(max_length=255),
        ),
    ]
