# Generated by Django 5.1.1 on 2024-11-14 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subkategori_tipe_alter_subkategori_kategori_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subkategori',
            name='kategori',
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
        migrations.DeleteModel(
            name='Subkategori',
        ),
    ]
