# Generated by Django 5.1.3 on 2024-11-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='birth_date',
            field=models.DateField(default='2006-11-11'),
            preserve_default=False,
        ),
    ]
