# Generated by Django 5.1.3 on 2024-11-11 04:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='pekerja',
            name='address',
            field=models.CharField(default='aaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pekerja',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pekerja',
            name='gender',
            field=models.CharField(choices=[('L', 'Laki'), ('P', 'Perempuan')], default='L', max_length=1),
        ),
        migrations.AddField(
            model_name='pekerja',
            name='phone_number',
            field=models.CharField(default='000', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengguna',
            name='address',
            field=models.CharField(default='aaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengguna',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengguna',
            name='gender',
            field=models.CharField(choices=[('L', 'Laki'), ('P', 'Perempuan')], default='L', max_length=1),
        ),
        migrations.AddField(
            model_name='pengguna',
            name='phone_number',
            field=models.CharField(default='000', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
