# Generated by Django 5.1.3 on 2024-11-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saldo_mypay',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('L', 'Laki'), ('P', 'Perempuan')], default='L', max_length=1),
        ),
    ]
