# Generated by Django 5.1.3 on 2024-11-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_address_remove_user_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pekerja',
            name='gender',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='L', max_length=1),
        ),
    ]
