# Generated by Django 5.1.3 on 2024-11-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='saldo_mypay',
        ),
        migrations.AddField(
            model_name='user',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
