# Generated by Django 5.1.3 on 2024-11-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_pekerja_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pekerja',
            name='bank_number',
            field=models.CharField(max_length=20),
        ),
    ]
