# Generated by Django 5.1.1 on 2024-11-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_pekerja_bank_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saldo_mypay',
            field=models.IntegerField(default=0),
        ),
    ]
