# Generated by Django 5.1.3 on 2024-11-06 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subkategori_layanan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Mencari Pekerja Terdekat', 'Mencari Pekerja Terdekat'), ('Menunggu Pembayaran', 'Menunggu Pembayaran'), ('Pesanan Selesai', 'Pesanan Selesai'), ('Dibatalkan', 'Dibatalkan')], default='Mencari Pekerja Terdekat', max_length=50)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_code', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('sesi_layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subkategori_layanan.sesilayanan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
