# Generated by Django 5.1.3 on 2024-11-07 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan_jasa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PemesananJasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pemesanan', models.DateField(auto_now_add=True)),
                ('diskon', models.CharField(blank=True, max_length=50, null=True)),
                ('total_pembayaran', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metode_pembayaran', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Menunggu Pembayaran', 'Menunggu Pembayaran'), ('Mencari Pekerja Terdekat', 'Mencari Pekerja Terdekat'), ('Pesanan Selesai', 'Pesanan Selesai')], default='Menunggu Pembayaran', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
