# Generated by Django 5.1.3 on 2024-11-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan_jasa', '0002_pemesananjasa_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemesananjasa',
            name='user',
        ),
        migrations.AddField(
            model_name='pemesananjasa',
            name='testimoni_dibuat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pemesananjasa',
            name='diskon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pemesananjasa',
            name='status',
            field=models.CharField(choices=[('menunggu_pembayaran', 'Menunggu Pembayaran'), ('mencari_pekerja', 'Mencari Pekerja Terdekat'), ('selesai', 'Pesanan Selesai'), ('dalam_proses', 'Dalam Proses')], default='dalam_proses', max_length=20),
        ),
        migrations.AlterField(
            model_name='pemesananjasa',
            name='tanggal_pemesanan',
            field=models.DateField(),
        ),
    ]
