# Generated by Django 5.1.3 on 2024-11-25 13:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan_jasa', '0004_pemesananjasa_pengguna'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPesanan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pemesananjasa',
            name='status',
        ),
        migrations.CreateModel(
            name='TRPemesananStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_waktu', models.DateTimeField(auto_now_add=True)),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pemesanan_jasa.statuspesanan')),
                ('id_tr_pemesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pemesanan_jasa.pemesananjasa')),
            ],
            options={
                'unique_together': {('id_tr_pemesanan', 'id_status')},
            },
        ),
    ]
