# Generated by Django 5.1.3 on 2024-12-01 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan_jasa', '0006_remove_pemesananjasa_testimoni_dibuat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trpemesananstatus',
            name='id_tr_pemesanan',
        ),
        migrations.RemoveField(
            model_name='trpemesananstatus',
            name='id_status',
        ),
        migrations.AlterUniqueTogether(
            name='trpemesananstatus',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='PemesananJasa',
        ),
        migrations.DeleteModel(
            name='StatusPesanan',
        ),
        migrations.DeleteModel(
            name='TRPemesananStatus',
        ),
    ]
